# Generated by Django 3.1.2 on 2020-10-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceName', models.CharField(max_length=255)),
                ('city', models.TextField(blank=True)),
                ('role', models.TextField(blank=True)),
                ('age', models.CharField(blank=True, max_length=4)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
