# Generated by Django 3.1.2 on 2020-10-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='maleNames',
            field=models.JSONField(null=True),
        ),
    ]
