# Generated by Django 3.1.2 on 2020-10-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0002_race_malenames'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='femaleNames',
            field=models.JSONField(null=True),
        ),
    ]
