# Generated by Django 3.1.1 on 2020-10-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0003_race_femalenames'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('aligment', models.CharField(max_length=255)),
                ('city', models.TextField(blank=True)),
                ('role', models.TextField(blank=True)),
                ('age', models.CharField(blank=True, max_length=4)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='race',
            name='age',
        ),
        migrations.RemoveField(
            model_name='race',
            name='city',
        ),
        migrations.RemoveField(
            model_name='race',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='race',
            name='role',
        ),
        migrations.AddField(
            model_name='race',
            name='familyNames',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='names',
            field=models.JSONField(null=True),
        ),
    ]
