# Generated by Django 3.1.1 on 2020-10-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0004_auto_20201003_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='aligment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
