# Generated by Django 3.1.1 on 2020-10-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0005_auto_20201003_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='familyNames',
        ),
        migrations.RemoveField(
            model_name='race',
            name='femaleNames',
        ),
        migrations.RemoveField(
            model_name='race',
            name='maleNames',
        ),
        migrations.RemoveField(
            model_name='race',
            name='names',
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npc.race')),
            ],
        ),
        migrations.CreateModel(
            name='MaleNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maleName', models.CharField(max_length=255)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npc.race')),
            ],
        ),
        migrations.CreateModel(
            name='FemaleNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('femaleName', models.CharField(max_length=255)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npc.race')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyName', models.CharField(max_length=255)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npc.race')),
            ],
        ),
    ]
