# Generated by Django 3.1.1 on 2020-11-15 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0007_npc_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='npc.race'),
        ),
    ]
