# Generated by Django 3.1.1 on 2020-12-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='pdf',
            field=models.FileField(max_length=255, upload_to='C:\\Users\\Amand\\Desktop\\Programming\\DNDtracker\\media'),
        ),
    ]
